### ISSUE TITLE
Feat: Dice Roller - Implementing Text-Based User Interface

### ISSUE THREAD

**Issue by Heyeso** [Heyeso/python-projects#3]
**Problem**
Dice Roller - Implementing Text-Based User Interface

**Feature Problem**
The goal of this project is to create a dice-rolling simulator app with a minimal yet user-friendly text-based user interface (TUI). The TUI will allow the user to specify the number of six-sided dice they would like to roll and will display the result in the form of an ASCII diagram.

**Task Checklist**
- [x]  Create a single file called dice.py in a directory of your choice in your file system.
- [x]  Implement a prompt for the user to choose how many six-sided dice to roll using Python's input() function.
- [x]  Parse and validate the user's input.
- [x]  Create a user-defined function called rollDice() to run the dice-rolling simulation using Python's random module.
- [x]  Create a user-defined function called generateDiceFaces() to generate an ASCII diagram with the resulting dice faces.
- [x]  Display the diagram of dice faces on the screen using Python's print() function.
- [x]  Test the app to ensure it is working as expected.
